import { resolveTeamLogo } from "@/lib/data/team-logos";
import { SM_LEAGUE } from "@/lib/sportmonks/constants";
import { formatRoundLabel, leagueMetaForId } from "./league-meta";
import type { LiveScoreMatch, LiveScoresBoardPayload } from "./types";

function logoFor(name: string): string | null {
  const url = resolveTeamLogo({ id: 0, name: name });
  return url || null;
}

/**
 * Demo cards using fields we can collect from SportMonks livescores/inplay
 * (league, venue, round, participants + logos, scores, events timeline, live stats).
 */
export function buildLiveScorePlaceholders(): LiveScoreMatch[] {
  const pl = leagueMetaForId(SM_LEAGUE.PREMIER_LEAGUE);
  const ered = leagueMetaForId(SM_LEAGUE.EREDIVISIE);
  const serie = leagueMetaForId(SM_LEAGUE.SERIE_A);

  return [
    {
      matchSmId: -1001,
      leagueName: pl.name,
      countryIso: pl.countryIso,
      countryName: pl.countryName,
      stadiumName: "Emirates Stadium",
      gameweek: 1,
      roundLabel: formatRoundLabel(1),
      homeTeamName: "Arsenal",
      awayTeamName: "Chelsea",
      homeTeamSmId: 19,
      awayTeamSmId: 18,
      homeLogoUrl: logoFor("Arsenal"),
      awayLogoUrl: logoFor("Chelsea"),
      homeScore: 2,
      awayScore: 1,
      statusLabel: "2nd Half",
      minute: 67,
      durationMinutes: 90,
      kickoffAt: null,
      isPlaceholder: true,
      timeline: [
        {
          id: 1,
          kind: "goal",
          side: "home",
          minute: 12,
          extraMinute: null,
          clockLabel: "12'",
          playerName: "Saka",
          relatedPlayerName: "Ødegaard",
          info: null,
        },
        {
          id: 2,
          kind: "yellow_card",
          side: "away",
          minute: 28,
          extraMinute: null,
          clockLabel: "28'",
          playerName: "Caicedo",
          relatedPlayerName: null,
          info: "Foul",
        },
        {
          id: 3,
          kind: "goal",
          side: "away",
          minute: 41,
          extraMinute: null,
          clockLabel: "41'",
          playerName: "Palmer",
          relatedPlayerName: "Madueke",
          info: null,
        },
        {
          id: 4,
          kind: "substitution",
          side: "home",
          minute: 58,
          extraMinute: null,
          clockLabel: "58'",
          playerName: "Trossard",
          relatedPlayerName: "Martinelli",
          info: null,
        },
        {
          id: 5,
          kind: "goal",
          side: "home",
          minute: 63,
          extraMinute: null,
          clockLabel: "63'",
          playerName: "Havertz",
          relatedPlayerName: "Saka",
          info: null,
        },
        {
          id: 6,
          kind: "yellow_card",
          side: "home",
          minute: 66,
          extraMinute: null,
          clockLabel: "66'",
          playerName: "Rice",
          relatedPlayerName: null,
          info: null,
        },
      ],
      homeMetrics: {
        possessionPct: 58,
        shots: 12,
        shotsOnTarget: 5,
        corners: 6,
        xg: 1.84,
      },
      awayMetrics: {
        possessionPct: 42,
        shots: 8,
        shotsOnTarget: 3,
        corners: 3,
        xg: 0.92,
      },
    },
    {
      matchSmId: -1002,
      leagueName: ered.name,
      countryIso: ered.countryIso,
      countryName: ered.countryName,
      stadiumName: "Johan Cruijff ArenA",
      gameweek: 2,
      roundLabel: formatRoundLabel(2),
      homeTeamName: "Ajax",
      awayTeamName: "PSV",
      homeTeamSmId: 629,
      awayTeamSmId: 680,
      homeLogoUrl: logoFor("Ajax"),
      awayLogoUrl: logoFor("PSV"),
      homeScore: 0,
      awayScore: 0,
      statusLabel: "1st Half",
      minute: 23,
      durationMinutes: 90,
      kickoffAt: null,
      isPlaceholder: true,
      timeline: [
        {
          id: 11,
          kind: "yellow_card",
          side: "away",
          minute: 9,
          extraMinute: null,
          clockLabel: "9'",
          playerName: "Schouten",
          relatedPlayerName: null,
          info: null,
        },
        {
          id: 12,
          kind: "missed_penalty",
          side: "home",
          minute: 18,
          extraMinute: null,
          clockLabel: "18'",
          playerName: "Bergwijn",
          relatedPlayerName: null,
          info: null,
        },
      ],
      homeMetrics: {
        possessionPct: 51,
        shots: 4,
        shotsOnTarget: 1,
        corners: 2,
        xg: 0.71,
      },
      awayMetrics: {
        possessionPct: 49,
        shots: 3,
        shotsOnTarget: 0,
        corners: 1,
        xg: 0.22,
      },
    },
    {
      matchSmId: -1003,
      leagueName: serie.name,
      countryIso: serie.countryIso,
      countryName: serie.countryName,
      stadiumName: "San Siro",
      gameweek: 1,
      roundLabel: formatRoundLabel(1),
      homeTeamName: "Inter",
      awayTeamName: "AC Milan",
      homeTeamSmId: 2930,
      awayTeamSmId: 113,
      homeLogoUrl: logoFor("Inter"),
      awayLogoUrl: logoFor("AC Milan"),
      homeScore: 1,
      awayScore: 1,
      statusLabel: "HT",
      minute: 45,
      durationMinutes: 90,
      kickoffAt: null,
      isPlaceholder: true,
      timeline: [
        {
          id: 21,
          kind: "goal",
          side: "home",
          minute: 22,
          extraMinute: null,
          clockLabel: "22'",
          playerName: "Lautaro",
          relatedPlayerName: "Barella",
          info: null,
        },
        {
          id: 22,
          kind: "red_card",
          side: "away",
          minute: 34,
          extraMinute: null,
          clockLabel: "34'",
          playerName: "Tomori",
          relatedPlayerName: null,
          info: "Serious foul",
        },
        {
          id: 23,
          kind: "penalty",
          side: "away",
          minute: 45,
          extraMinute: 1,
          clockLabel: "45+1'",
          playerName: "Leão",
          relatedPlayerName: null,
          info: null,
        },
        {
          id: 24,
          kind: "substitution",
          side: "home",
          minute: 45,
          extraMinute: null,
          clockLabel: "45'",
          playerName: "Frattesi",
          relatedPlayerName: "Mkhitaryan",
          info: null,
        },
      ],
      homeMetrics: {
        possessionPct: 55,
        shots: 7,
        shotsOnTarget: 3,
        corners: 4,
        xg: 1.12,
      },
      awayMetrics: {
        possessionPct: 45,
        shots: 5,
        shotsOnTarget: 2,
        corners: 2,
        xg: 0.88,
      },
    },
  ];
}

export function placeholderLiveScoresBoard(): LiveScoresBoardPayload {
  return {
    matches: buildLiveScorePlaceholders(),
    syncedAt: null,
    source: "placeholder",
  };
}
